DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS UserPreferences;

CREATE TABLE User (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Mail NVARCHAR(255) UNIQUE NOT NULL,
    FirstName NVARCHAR(255) NOT NULL,
    LastName NVARCHAR(255) NOT NULL,
    BirthDate DATE,
    Psw NVARCHAR(255) NOT NULL
);

CREATE TABLE UserPreferences (
    UserID INTEGER,
    IdCocktail NVARCHAR(255) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES User(Id),
    FOREIGN KEY (IdCocktail) REFERENCES Cocktail(id),
    PRIMARY KEY (UserID)
);