# Fase 1: Costruzione dell'app .NET
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /NoisyBobs
EXPOSE 80

# Fase 2: Build dell'app
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["CocktailApp/CocktailApp.csproj", "CocktailApp/"]
RUN dotnet restore "CocktailApp/CocktailApp.csproj"
COPY . .
WORKDIR "/src/CocktailApp"
RUN dotnet build "CocktailApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CocktailApp.csproj" -c Release -o /app/publish

# Fase 3: Configurazione finale e avvio
FROM base AS final
WORKDIR /NoisyBobs
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CocktailApp.dll"]
