DROP TABLE IF EXISTS Message;

CREATE TABLE Message (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Sender TEXT NOT NULL,
    MessageText TEXT NOT NULL,
    SendingTime DATETIME DEFAULT CURRENT_TIMESTAMP
);
