DROP TABLE IF EXISTS User;

CREATE TABLE User (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Mail NVARCHAR(255) UNIQUE NOT NULL,
    UserName NVARCHAR(255) UNIQUE NOT NULL,
    BirthDate DATE,
    Psw NVARCHAR(255) NOT NULL,
    AcceptedTerms BOOLEAN NOT NULL DEFAULT 0
);

