DROP TABLE IF EXISTS User;

CREATE TABLE User (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Mail NVARCHAR(255) UNIQUE NOT NULL,
    FirstName NVARCHAR(255) NOT NULL,
    LastName NVARCHAR(255) NOT NULL,
    BirthDate DATE,
    Psw NVARCHAR(255) NOT NULL
);

